ALTER TABLE food_logs ADD COLUMN IF NOT EXISTS protein DECIMAL(6,2) DEFAULT 0;
ALTER TABLE food_logs ADD COLUMN IF NOT EXISTS fat DECIMAL(6,2) DEFAULT 0;
ALTER TABLE food_logs ADD COLUMN IF NOT EXISTS carbs DECIMAL(6,2) DEFAULT 0;

ALTER TABLE food_templates ADD COLUMN IF NOT EXISTS protein DECIMAL(6,2) DEFAULT 0;
ALTER TABLE food_templates ADD COLUMN IF NOT EXISTS fat DECIMAL(6,2) DEFAULT 0;
ALTER TABLE food_templates ADD COLUMN IF NOT EXISTS carbs DECIMAL(6,2) DEFAULT 0;

ALTER TABLE daily_food_entries ADD COLUMN IF NOT EXISTS protein DECIMAL(6,2) DEFAULT 0;
ALTER TABLE daily_food_entries ADD COLUMN IF NOT EXISTS fat DECIMAL(6,2) DEFAULT 0;
ALTER TABLE daily_food_entries ADD COLUMN IF NOT EXISTS carbs DECIMAL(6,2) DEFAULT 0;
